// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQY2jak6za3lY1TSs34cRahiSoomkjuuQ',
    appId: '1:825731539103:web:87e638cb36a091fb8e42aa',
    messagingSenderId: '825731539103',
    projectId: 'addeen-c65a5',
    authDomain: 'addeen-c65a5.firebaseapp.com',
    storageBucket: 'addeen-c65a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS3vyD4fu8bxH8xRPGrW0Is_5siDuwEBs',
    appId: '1:825731539103:android:a10aff53375658628e42aa',
    messagingSenderId: '825731539103',
    projectId: 'addeen-c65a5',
    storageBucket: 'addeen-c65a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVTXof5m09ij6-u8aJfn8rgTZ3IXhZC0k',
    appId: '1:825731539103:ios:08dd0f64bc17e8038e42aa',
    messagingSenderId: '825731539103',
    projectId: 'addeen-c65a5',
    storageBucket: 'addeen-c65a5.firebasestorage.app',
    iosBundleId: 'com.example.quizUniversity',
  );
}
